---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: staging/v1.x
  - package-ecosystem: npm
    directory: /grafana/rmf-app
    schedule:
      interval: daily
    target-branch: staging/v1.x
  - package-ecosystem: gomod
    directory: /grafana/rmf-app
    schedule:
      interval: daily
    target-branch: staging/v1.x